"""add root_cause table

Revision ID: d09dec67d2cc
Revises: 9d3317f82bd4
Create Date: 2020-07-27 14:47:28.210164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd09dec67d2cc'
down_revision = '9d3317f82bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.drop_index('id', table_name='patients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id', 'patients', ['id'], unique=True)
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.alter_column('patients', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
